[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt --no-cache-dir"]

[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.pip"]

[providers]
python = true

[start]
cmd = "python model_api.py"
